### ISSUE TITLE
Problem in downloading images

### ISSUE THREAD

**Issue by Noman-saeed** [fastrde/phonegap-downloader#1]
I am developing an App. in which user can download images from google search or any other src that is available in App. So my requirement is that i want to download multiple images but one by one. first image downloads perfectly but when i press download on second image it does nothing.

**Comment by fastrde** [comment]
Tried it by myself and for me it's possible to download more then one image one by one.
Below you can find some snippets of code extracted from my Test-App. 
Can you try something simple like that or post the relevant code-parts so i can have a look.

Init-Function

```
onDeviceReady: function() {
     downloader.init({
          fileSystem: cordova.file.dataDirectory,
          folder: "pics"  
        });
}
```

Download-Function

```
download: function(url){
        console.log("Downloading "+url);
        downloader.get(url);
}   
```

and multiple Links with 

```
 onclick="app.download('http://somehost.org/somepicture.jpg');"
```

**Comment by Noman-saeed** [comment]
Thank you for your reply. You really helped me. There was a mistake on my end. I figured the problem by looking at your code. Thank you again
