### ISSUE TITLE
Is it possible to abort the current download item?

### ISSUE THREAD

**Issue by snese** [fastrde/phonegap-downloader#10]
Hi,

Is it possible to abort the current download process?

I delete the downloading file the scenario **downloader** should stop download process but the real situation is **downloader** download the file anyway in the background.

Thanks, guys.

**Comment by fastrde** [comment]
now it's possible. Just fetch version 0.2.1 from npm and call `downloader.abort()`. Also see updated examples in readme.

**Comment by snese** [comment]
Wow, great work!

You guys rock
