### ISSUE TITLE
downloaded file is not in folder set in plugin settings

### ISSUE THREAD

**Issue by cinder92** [fastrde/phonegap-downloader#13]
Hi, im using your plugin to download one image but it seems that is not storage in my folder

```
downloader.init({folder: "covers"});
downloader.get(track.album.image[2]['#text']);

var cover = "covers/"+getFilename(track.album.image[2]['#text'])+'.png';
```

when im trying to get this file from folder "covers/md5hash.png", is not working

this url is form ask.fm

**Comment by fastrde** [comment]
I tried it with a fresh cordova project and add 2 lines

```
downloader.init({folder: "covers"});
downloader.get("http://www.ikea.com/robots.txt");
```

folder "covers" appears and robots.txt is stored inside. 
But default filesystem ist LocalFileSystem.PERSISTENT and not your www-root.
Have a look at filesystemURL parameter and cordova.file plugin to change the directory to fit your needs

**Comment by cinder92** [comment]
did you mean that i need to create a folder "covers" in phone, not in www app folder?

**Comment by fastrde** [comment]
you don't need to create a covers folder at all. The plugin does it for you. But you have to tell the plugin where, when not in the default location "LocalFileSystem.PERSISTENT". Filesystems and crossplatform directory-paths described in cordova-plugin-file. So it's no issue in my plugin.

**Comment by prasanthnath1988** [comment]
Hi Fastrde,

I have installed the plugin, and was able to Instantiate the following function.
But It does not works

downloader.init({folder: "testApp"});
downloader.get("http://yourhost.de/some.txt");

document.addEventListener("DOWNLOADER_downloadSuccess", function(event){
  var data = event.data;
console.log(JSON.stringify(data));
});

I am not getting any JSON data on "DOWNLOADER_downloadSuccess" or "DOWNLOADER_downloadError"

**Comment by fastrde** [comment]
Are you sure that the events fire? (add the listener before you download a file)
Permissions set correctly in Manifest on Android?
You should receive a `cordova.fileEntry`[1] as `event.data` on success. Have you tried to display `event.data.name`?

[1] http://docs.phonegap.com/en/edge/cordova_file_file.md.html#FileEntry

**Comment by prasanthnath1988** [comment]
no the event is not getting fired

**Comment by fastrde** [comment]
> (add the listener before you download a file)
> Permissions set correctly in Manifest on Android?
> You should receive a cordova.fileEntry[1] as event.data on success. Have you tried to display event.data.name?

correction: event.data[0].name

> [1] http://docs.phonegap.com/en/edge/cordova_file_file.md.html#FileEntry

**Comment by prasanthnath1988** [comment]
Can you plz tell me what all permission do I need to set in Manifest File

**Comment by prasanthnath1988** [comment]
I have set these Permissions 

```
<uses-feature android:name="android.hardware.telephony" android:required="false" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="android.permission.RECEIVE_WAP_PUSH" />
    <uses-permission android:name="android.permission.RECEIVE_MMS" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.WRITE_SMS" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by fastrde** [comment]
What's about `android.permission.INTERNET`?

**Comment by prasanthnath1988** [comment]
Actually with these permissions Cordova.file plugin is working and I was able to download the file
fileTransfer.download();

Ok, let me try by adding this permission

**Comment by prasanthnath1988** [comment]
Thanks for Quick reply :)

**Comment by prasanthnath1988** [comment]
No, still not able to make it work.
please add few more details to use the plugin or plz add a demo project folder of working code.

**Comment by fastrde** [comment]
again: have you add the listener _before_ you call `downloader.get()`?

fully working just tested code

```
downloader.init({folder: "testApp"});
document.addEventListener("DOWNLOADER_downloadSuccess", function(event){
  var data = event.data;
  console.log(data);
}); 
downloader.get("http://download.thinkbroadband.com/5MB.zip");
```

**Comment by prasanthnath1988** [comment]
Yes, tried the same. but no luck.

I guess there may be some issue with the local file system (persistent - folder) at my end.
The folder name I have mentioned is the App folder name. may be it is not getting the path to store the file.

**Comment by akhilesh1989** [comment]
I also tried the same, but not getting anything.
My Code: 
downloader.init({fileSystem: cordova.file.applicationStorageDirectory, folder: "testapp", unzip: true});
        document.addEventListener("DOWNLOADER_downloadError", function(event){
                                  var data = event.data;
                                  alert(data);
                                  }); 
        downloader.get("http://172.27.46.187:8080/ZipFile.zip");

I guess, it's not even downloading because event is not fired.
please add few more details to use the plugin or please add a demo project folder of working code.

**Comment by pedropamn** [comment]
I get: Uncaught ReferenceError: DOWNLOADER_downloadSuccess is not defined
