### ISSUE TITLE
Docs show folder as a simple String but a fileEntry type is required

### ISSUE THREAD

**Issue by Barryrowe** [fastrde/phonegap-downloader#15]
Docs all show the folder as a simple string parameter:

This fails with the error:  

> Downloader.localFolder.toURL is not a function

Looking at the source a folder instance of fileEntry is required:

```
 /**
   * sets the Folder for storing the downloads
   * @param {cordova-plugin-file.FileEntry} folder
   */
  setFolder: function(folder) {
    Downloader.localFolder = folder;
  },
```

Docs need to be updated with an example of grabbing the actual folder FileEntry reference, or at least a link to such documentation.

**Comment by Barryrowe** [comment]
Looks like this is not 100% correct. However, on the first call, if the creation of the directory takes too long, there is a race condition where Downloader.localFolder.toURL() is called before it's been reset to the FileEntry object from creating it.

**Comment by mramonlopez** [comment]
I have found the same problem always in the second downloaded file. After messing around the plugin code, I have found a solution:

```
download(url) {
    let initialized = function (event) {
        window.downloader.get(url);
        event.target.removeEventListener(event.name, initialized);
    };

    document.addEventListener('DOWNLOADER_initialized', initialized);

    window.downloader.init({
        folder: './',
        unzip: true,
        check: false,
        noMedia: true,
        wifiOnly: false
    });
}
```

I think this is not a issue. It's a not well documented feature.

**Comment by fastrde** [comment]
Thank you for the report.

hmm. I'm a little bit confused. This is what i do already internal in the load function

```
if (!Downloader.isInitialized()) { // Not initialized?
  document.addEventListener("DOWNLOADER_initialized", function onInitialized(event) { //wait for it
    event.target.removeEventListener("DOWNLOADER_initialized", onInitialized, false); //remove listener
    Downloader.load(url, md5); //start loading
  }, false);
  return;
}
```

`downloader.initialized` is set to true after `Downloader.localFolder` is set to the fileEntry Object.
