### ISSUE TITLE
getMultipleFiles Event Listener

### ISSUE THREAD

**Issue by dpz3579** [fastrde/phonegap-downloader#16]
`getMultipleFiles` has an event Listener as 
`DOWNLOADER_downloadSuccess`
but actually we don't have an event Listener as when all the 5-6 files that were specified as set are downloaded completely.
please do let me know if there is some event listener like that, as i'm stuck badly...

Thanks

**Comment by fastrde** [comment]
Sorry there is no Event for "all files completed" yet. The only thing you can do to workaround that at the moment is count the files you multidownload and the number of `DOWNLOADER_downloadSuccess` Events.

**Comment by dpz3579** [comment]
yes we are doing that only, but were facing certain challenges..
anyways thanks for the reply... :smile: 

appreciate your help for the same.. :+1:
