### ISSUE TITLE
How to know the path (ios)

### ISSUE THREAD

**Issue by JSkeeper** [fastrde/phonegap-downloader#18]
Hi, I have problem while using your plugins in ios.

when I init, I can find my folder in android.

But in ios,I don't know the path.

I want to use another plugins to open my downloaded file, need my file path, thanks.

**Comment by fastrde** [comment]
my plugin is only a wrapper to make downloading easier. Filesystems are provided from the underlaying cordova file plugin[1]. There you can find documentation how to use the filesystems and paths OS independent.

[1]https://github.com/apache/cordova-plugin-file
