### ISSUE TITLE
After DOWNLOADER_downloadError event is not possible to  process downloader.get succesfully

### ISSUE THREAD

**Issue by r0boto** [fastrde/phonegap-downloader#2]
Hi,
thanks for your useful plugin, i faced with one problem, here is the description of the issue:

If connection is lost during the download process is triggered DOWNLOADER_downloadError event. 

After this i'm waiting for event online to make default init for downloader again (it means add download listeners and init downloader). 

But if function downloader.get  is triggered second time, nothing is happend, event DOWNLOADER_downloadProgress is not called, no exception, just nothing..

**Comment by fastrde** [comment]
Sorry i messed up the internal status variables and leave them uncleared after an error occured... should be fixed now

**Comment by pedropamn** [comment]
Hi

In this case, how i can re-init the proccess? I have to put `downloader.init` again, inside `DOWNLOADER_downloadError `?
