### ISSUE TITLE
Zip Password Protection - Feature Request

### ISSUE THREAD

**Issue by bigt11** [fastrde/phonegap-downloader#23]
Any plans to support password protected zip files?  I would like to deliver encrypted - password protected zip files to a device, then obviously decrypt - unzip.  This plugin does exactly what I am looking for minus the password protection.  Any suggestions?

**Comment by fastrde** [comment]
this plugin needs a complete rewrite before i want to add more features... sorry, but at the moment there is no time for hobby projects
