### ISSUE TITLE
Error - Plugin error (you probably need to remove plugin files from your app)

### ISSUE THREAD

**Issue by mohamedzaher88** [fastrde/phonegap-downloader#27]
i use phonegap build 

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-fastrde-downloader" via npm Installing "cordova-plugin-fastrde-downloader" at "0.2.1" for android Failed to install 'cordova-plugin-fastrde-downloader': CordovaError: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^1.0.1". Try --force to use installed plugin as dependency. at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:581:33 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:509:49 at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9) Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^1.0.1". Try --force to use installed plugin as dependency. - You can fix this here

**Comment by mhudnell** [comment]
I also get this with phonegap build, please update the cordova-plugin-file dependency

**Comment by zwallacedev** [comment]
👍  to this, can we see a fix implemented? Or can I push a PR to get this updated?

**Comment by mohamedzaher88** [comment]
the same problem !!!! 
i update my config.xml and use the last version


<gap:plugin name="cordova-plugin-file" spec="~4.3.3" source="npm" />
<gap:plugin name="cordova-plugin-file-transfer" spec="~1.6.3" source="npm" />
<gap:plugin name="cordova-plugin-fastrde-downloader"  source="npm" />


phonegap build view this error

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-fastrde-downloader" via npm Installing "cordova-plugin-fastrde-downloader" at "0.2.1" for android Failed to install 'cordova-plugin-fastrde-downloader': CordovaError: Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^1.0.1". Try --force to use installed plugin as dependency. at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:581:33 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:509:49 at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9) Version of installed plugin: "cordova-plugin-file@4.3.3" does not satisfy dependency plugin requirement "cordova-plugin-file@^1.0.1". Try --force to use installed plugin as dependency. - You can fix this here

**Comment by fastrde** [comment]
sorry, I don't have the time at the moment to maintain this plugin activly. PRs are welcome.
