### ISSUE TITLE
How to use cordova-plugin-fastrde-downloader

### ISSUE THREAD

**Issue by daniel-inacio** [fastrde/phonegap-downloader#4]
Hello everybody, I would like to have an example of how to use the cordova-plugin-fastrde-downloader  because I could not make it work

**Comment by fastrde** [comment]
hi,
did the examples in the readme not working?
Or can you explain your problem in detail?

**Comment by daniel-inacio** [comment]
My code is:

   $("#btn_download" ).click(function() {
          downloader.init({folder: "myfolder", unzip: true});
          downloader.get("sergios.jelasticlw.com.br/_lib/file/arquivos/israco.zip");
});

**Comment by fastrde** [comment]
try

```
downloader.get("http://sergios.jelasticlw.com.br/_lib/file/arquivos/israco.zip");
```

this should work
