### ISSUE TITLE
Phonegap Bulld

### ISSUE THREAD

**Issue by daksamedia** [fastrde/phonegap-downloader#5]
Hi @fastrde ,
How to install your plugin ro my Phonegap Build project?
Could you tell detailly?

Thank in advanced,

Daksa Media.

**Comment by fastrde** [comment]
sorry i don't use Phonegap build. 
Does it not work like the "plugin add" command at Phonegap-CLI?

**Comment by fastrde** [comment]
closed due to inactivity.
