### ISSUE TITLE
Can't get an instance of the plugin

### ISSUE THREAD

**Issue by aj1717** [fastrde/phonegap-downloader#8]
Hi,
[SOLVED]
I add the plugin to my project, however, there's no way I can access it.
I tried:
downloader.
window.downloader...
cordova.plugins.downloader...
window.plugins.downloader...
cordova.require('downloader')....

unfortunately, all return null. I have other plugins and they all work fine apart from this.
Could you please let me know how I can access this plugin after I add it to my project?

Thanks.

**Comment by fastrde** [comment]
`downloader.` is the right choice. Did you install the plugin via cmd-line? 
What does 

```
cordova plugin list
```

say? 
Can you try to reinstall it via cmd-line and look for something going wrong?

What's about https://github.com/MobileChromeApps/cordova-plugin-zip/issues/58? 
Looks like you have other plugins that not work fine.
is it possible that the problem is in your enviroment?

**Comment by aj1717** [comment]
Thanks for the reply.

I use Intel XDK and import plugins automatically. All plugins work apart from this one.
regarding the plugin list, I run the script:

JSON.stringify(cordova.require('cordova/plugin_list').metadata, null, 1);

and get the following list:

{ "cordova-plugin-device": "1.1.0", "cordova-plugin-splashscreen": "2.1.0", "cordova-plugin-statusbar": "2.0.0", "de.fastr.phonegap.plugins.downloader": "0.1.5", "cordova-plugin-file": "2.1.0", "cordova-plugin-file-transfer": "1.3.0", "cordova-plugin-network-information": "1.0.1", "cordova-plugin-zip": "3.0.0", "cordova-plugin-fastrde-md5": "0.2.0" }

I still am unable to access downloader?

Many thanks,

**Comment by aj1717** [comment]
Plugin  MobileChromeApps/cordova-plugin-zip has the same issue.
It seems that the www/js script doesn't export the plugin properly.
All other plugins export it like
window.plugins.someplugin = new somePlugin()
or
module.exports = new someplugin

but these lines don't appear in your plugin and the Zip plugin.
Therefore, it can't be accessed.

**Comment by aj1717** [comment]
There seems to be a problem with Cordova CLI 5.1.1 on Intel XDK.
The plugin can't be accessed on it.
However, when I change to Cordova 4.1.2, it is working....

**Comment by aj1717** [comment]
My bad,
[SOLVED]
seems the problem is only with the folder locations.
You have to convert the folder to URL, folder.toURL() and use it to unzip files to.
If I try cordova.file.dataDirectory as folder to unzip things, then I get an error.

So that's the main problem.
