### ISSUE TITLE
Callback after download

### ISSUE THREAD

**Issue by distrilog** [fastrde/phonegap-downloader#9]
Hi,

It's possible to add callback fonction after get and getMultipleFiles ?

Best regards,
Nicolas

**Comment by fastrde** [comment]
it was a design decision not to use callbacks. So if you want to call a function when a file is downloaded you have to register the `downloadSuccess` and/or `downloadError` Event. The downloadSuccess Event sends a cordova.fileEntry object of the saved file.

```
document.addEventListener("DOWNLOADER_downloadSuccess",  yourCallback, false);
```

**Comment by distrilog** [comment]
Thanks :)
